name: DevOps Lab workflow

on:
 workflow_dispatch:

jobs:
  echo-steps:
   runs-on: ubuntu-latest
   steps:
     - name: First Step
       run: echo "This is first step"

     - name: Second Step
       run: echo "this is second step"
